INSERT INTO `smornstein` (`smornsteinid`, `smornsteinname`) VALUES
(0, 'None'),
(1, 'Anor Londo Attorneys'),
(2, 'Asterix & Obelix'),
(3, 'Atlas & P-body'),
(4, 'Biggie Smalls'),
(5, 'Fatboy Slim'),
(6, 'Fatman & Robin'),
(7, 'Fuck This I Quit'),
(8, 'James and the Giant Peach'),
(9, 'Jay & Silent Bob'),
(10, 'Jonah and the Whale'),
(11, 'Knight and the Round Table'),
(12, 'Laurel & Hardy'),
(13, 'Penn & Teller'),
(14, 'Pikachu & Snorlax'),
(15, 'Ren & Stimpy'),
(16, 'Spade & Farley'),
(17, 'Super Londo Bros'),
(18, 'Thunder & Thighs'),
(19, 'Timon & Pumba');